# Generated by Django 4.2.4 on 2024-06-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "hospital_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "Hospital",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licence_number", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "driver_photo",
                    models.ImageField(null=True, upload_to="driver_photos/"),
                ),
                (
                    "hospital_related_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_details.hospital",
                    ),
                ),
                (
                    "user_driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Driver",
            },
        ),
        migrations.CreateModel(
            name="cc_person",
            fields=[
                (
                    "cc_id",
                    models.BigAutoField(
                        auto_created="True", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cc_gov_id",
                    models.CharField(max_length=50, null="True", unique="True"),
                ),
                ("cc_image", models.ImageField(null="True", upload_to="")),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("photo", models.ImageField(null=True, upload_to="cc_photos/")),
                (
                    "user_cc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Customer Care Person",
            },
        ),
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "ambulance_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("ambulance_number", models.CharField(max_length=20, unique=True)),
                (
                    "ambulance_size",
                    models.CharField(
                        choices=[("B", "Big"), ("M", "Medium")], max_length=1
                    ),
                ),
                ("ambulance_model", models.CharField(max_length=50)),
                (
                    "ambulance_photo",
                    models.ImageField(null=True, upload_to="ambulance_photos/"),
                ),
                ("bystander_1", models.CharField(max_length=50, null="False")),
                ("bystander_2", models.CharField(max_length=50, null="False")),
                ("bystander_3", models.CharField(max_length=50, null="True")),
                ("bystander_4", models.CharField(max_length=50, null="True")),
                (
                    "driver_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_driver",
                        to="case_details.driver",
                    ),
                ),
                (
                    "driver_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_driver",
                        to="case_details.driver",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_details.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "Ambulance",
            },
        ),
    ]
