# Generated by Django 4.2.4 on 2024-06-17 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "case_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("Patient_name", models.CharField(max_length=35)),
                ("poc", models.CharField(max_length=35)),
                (
                    "accident_type",
                    models.CharField(
                        choices=[
                            ("VEH", "Vehicle Collision"),
                            ("FAL", "Fall"),
                            ("BUR", "Burn"),
                            ("CUT", "Laceration"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=3,
                    ),
                ),
                (
                    "patient_severity",
                    models.CharField(
                        choices=[
                            ("CRT", "Critical"),
                            ("SR", "Serious"),
                            ("MD", "Mild"),
                            ("MIN", "Minor"),
                        ],
                        default="MIN",
                        max_length=3,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("time_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Open"), (1, "Closed")], default=0
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("first_responder_notes", models.TextField(blank=True, null=True)),
                (
                    "ambulance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="case_details.ambulance",
                    ),
                ),
                (
                    "assigned_cc_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="case_details.cc_person",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="case_details.driver",
                    ),
                ),
            ],
            options={
                "db_table": "Case",
            },
        ),
    ]
