# Generated by Django 4.2.4 on 2024-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0002_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="phone_number",
        ),
    ]
