# Generated by Django 4.2.4 on 2024-06-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0003_remove_driver_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="hospital_related_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="case_details.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
