# Generated by Django 4.2.4 on 2024-06-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0004_alter_driver_hospital_related_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
