# Generated by Django 4.2.4 on 2024-06-19 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0005_alter_driver_licence_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="licence_number",
            new_name="license_number",
        ),
    ]
