# Generated by Django 4.2.4 on 2024-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0006_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cc_person",
            name="cc_gov_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
