# Generated by Django 4.2.4 on 2024-07-27 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0008_driver_case_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cc_person",
            name="cc_image",
        ),
    ]
