# Generated by Django 4.2.4 on 2024-07-28 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0011_remove_case_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="hospital_related_to",
        ),
    ]
