# Generated by Django 4.2.4 on 2024-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0012_remove_driver_hospital_related_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="current_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
