# Generated by Django 4.2.4 on 2024-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_details", "0013_driver_current_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_tracking",
            field=models.BooleanField(default=False),
        ),
    ]
